#!/usr/bin/node

const dbClient = require('../utils/db');

class UsersController {
    static async postNew(req, res) {
        const { email, password } = req.body
    }
   
module.exports = UsersController;
